import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

"""
That thing was generated by ChatGPT all I did was find the width
"""

# Load data
filename = 'src/le-calme-avant-la-tempest.bin'
data = np.fromfile(filename, dtype=np.int16)

# Just work directly with 1D data
# Normalize to 0-255
data_norm = (data - data.min()) / (data.max() - data.min()) * 255
data_norm = data_norm.astype(np.uint8)

# Assume width based on autocorrelation
width = 396  # try multiples of 198, or just 198 to test

# Cut data to match full lines
num_pixels = (len(data_norm) // width) * width
data_norm = data_norm[:num_pixels]

# Reshape
image = data_norm.reshape((-1, width))

# Save or display as grayscale
img = Image.fromarray(image, mode='L')
img.save('output_image.png')
